### PR TITLE
Partner 1

### PR DESCRIPTION
**Pull request by iammouaz**
What i Have done :

- Create Login Page 
- Create Rent A Car Page
- Create Cars List Page
- Create Add & Remove Car Page
- 
- Connect Rent & Remove & Add Car with back-end End Point

### CODE REVIEW

**Comment by Maclenn77** [comment]
Hi, @iammouaz 

I'm not able to log in from my computer. As I watched how you log in in your computer, I don't know which could be the problem. Could you also check, @lu-jim ?

**Comment by lu-jim** [comment]
Hello @iammouaz !

As @Maclenn77 experienced, I am also not able to log into the app. Please let us know if there is any previous setup on the app that we need to take care of, or if we are overlooking anything.

**Comment by iammouaz** [comment]
@lu-jim @Maclenn77 Can you Guys try now Please

**Comment by Maclenn77** [comment]
Problem solved.

**Pull request merged**
